### ISSUE TITLE
How to translate this project for specific languages?

### ISSUE THREAD

**Issue by dakeshi** [orta/pragmatic-testing#10]
Hi. @orta 

I find out this project while reading Artsy engineering contents.
I'm a big fan of Artsy and your members :smile: 
I always appreciate what Artsy did and will do in OSS commnunity :+1: 

This is a great writing and very helpful to many programmers.
So, I'd like to translate this project to Korean.
Is there some rules for contributing translation?
(ex : https://github.com/progit/progit2/blob/master/CONTRIBUTING.md)

**Comment by orta** [comment]
Hrm, interesting, thanks!

So, that's a good question, pro-git is a great example in this context - to do that properly I'd need to move this repo into an org, which isn't a particular problem for me. I've already just been [tweeted](https://twitter.com/ctietze/status/709386298788855808) to about making a contributions.md - so consider this high on my agenda!

**Comment by dakeshi** [comment]
Thanks @orta 

Hmm, What do you think about asciidoc format?
As Scott Chacon, proGit's main distributor, mentioned in [his story](https://medium.com/@chacon/living-the-future-of-technical-writing-2f368bd0a272#.m2ytlr1rs), I think that asciidoc is better choice for technical writing, supporting various formats than markdown.

**Comment by orta** [comment]
I think that's a good choice when you're working full time on a long technical book, but I'm optimising for existing developer tooling - using the most used text format, and writing simple ruby code to optimise things when needed

**Comment by dakeshi** [comment]
If you do not feel any problems with Markdown, it's OK. :smile: 
I just suggest another option to write focused on contents. 

But I just want you to know asciidoc is not for professional writers,  it is very easy as much as Markdown usage. And there are a lot of tools to support asciidocs representations. 

> If you use Alamofire to abstract away NSURLSession, why not use something to abstract away the nitty gritty of URLs, parameters, etc? -from Moya repo

**Comment by orta** [comment]
I respect that, but last time I stopped working on my book because I kept working on the tooling. 

It's easier to mess around with that then writing a chapter, so if I don't mess around with it, I focus more on the writing.

**Comment by dakeshi** [comment]
Sorry, I didn't think of that. I agree that converting and consisting of structure make another problem.
Maybe it's easier to solve these issues with Gitbook editor even though I need more test it.
Thanks for your considering on this issue.
